name: showcase
description: Showcase BDS
publish_to: none
homepage: https://www.grupobancolombia.com
version: 1.7.1+22
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.1
  shared_preferences: ^2.0.6
  bds_mobile:
    hosted:
      name: bds_mobile
      url: https://artifactory.apps.bancolombia.com/artifactory/api/pub/pub-bancolombia
    version: ^6.2.7
  bancolombia_foundations:
    hosted:
      name: bancolombia_foundations
      url: https://artifactory.apps.bancolombia.com/artifactory/api/pub/pub-bancolombia
    version: ^6.2.7
  bc_appcenter_plugin:
    hosted:
      name: bc_appcenter_plugin
      url: https://artifactory.apps.bancolombia.com/artifactory/api/pub/pub-bancolombia
    version: 5.1.0
  flutter_riverpod: ^2.4.10

dev_dependencies:
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_gherkin: ^2.0.0
  dart_code_linter: ^1.1.1
  build_runner: ^2.3.2
  flutter_lints: ^1.0.4
  flutter_markdown: ^0.6.18+2
  network_image_mock: ^2.1.1
  integration_test:
    sdk: flutter

dependency_overrides:
  url_launcher_web: 2.0.6
  intl: ^0.18.0
  # bds_mobile:
  #   path: ../bds_mobile/
  # bancolombia_foundations:
  #   path: ../bancolombia_foundations/
  # sufi_foundations:
  #   path: ../sufi_foundations/

flutter:
  uses-material-design: true